# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\skinn\Desktop\Диплом\pyqt5DesingProgram\PostAuthorize.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 40, 253, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reportSendButton = QtWidgets.QPushButton(self.layoutWidget)
        self.reportSendButton.setEnabled(False)
        self.reportSendButton.setObjectName("reportSendButton")
        self.verticalLayout.addWidget(self.reportSendButton)
        self.continueButton = QtWidgets.QPushButton(self.layoutWidget)
        self.continueButton.setEnabled(False)
        self.continueButton.setObjectName("continueButton")
        self.verticalLayout.addWidget(self.continueButton)
        self.newReport = QtWidgets.QPushButton(self.layoutWidget)
        self.newReport.setEnabled(True)
        self.newReport.setObjectName("newReport")
        self.verticalLayout.addWidget(self.newReport)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reportSendButton.setText(_translate("MainWindow", "Отправка отчета"))
        self.continueButton.setText(_translate("MainWindow", "Продолжить незаконченный отчет"))
        self.newReport.setText(_translate("MainWindow", "Новый отчет"))
